package com.rkss.rpg.coc.concepts.skill

sealed trait SkillName

case object Dodge extends SkillName
case object Meteorology extends SkillName
case object DriveAuto extends SkillName
case object NaturalWorld extends SkillName
case object ElectricalRepair extends SkillName
case object Navigate extends SkillName
case object Electronics extends SkillName
case object Occult extends SkillName
case object Engineering extends SkillName
case object OperateHeavyMachinery extends SkillName
case object FastTalk extends SkillName
case object Persuade extends SkillName
case object Pharmacy extends SkillName
case object FineArt extends SkillName
case object Photography extends SkillName
case object Accounting extends SkillName
case object Acting extends SkillName
case object AnimalHandling extends SkillName
case object Anthropology extends SkillName
case object Appraise extends SkillName
case object Archaeology extends SkillName
case object Artillery extends SkillName
case object Astronomy extends SkillName
case object Axe extends SkillName
case object Biology extends SkillName
case object Botany extends SkillName
case object Bow extends SkillName
case object Brawl extends SkillName
case object Chainsaw extends SkillName
case object Charm extends SkillName
case object Chemistry extends SkillName
case object Climb extends SkillName
case object ComputerUse extends SkillName
case object CreditRating extends SkillName
case object Cryptography extends SkillName
case object CthulhuMythos extends SkillName
case object Demolitions extends SkillName
case object Disguise extends SkillName
case object Diving extends SkillName
case object FirstAid extends SkillName
case object Flail extends SkillName
case object Flamethrower extends SkillName
case object Forensics extends SkillName
case object Forgery extends SkillName
case object Garrote extends SkillName
case object Geology extends SkillName
case object Handgun extends SkillName
case object HeavyWeapons extends SkillName
case object History extends SkillName
case object Hypnosis extends SkillName
case object Intimidate extends SkillName
case object Jump extends SkillName
case object Physics extends SkillName
case object ReadLips extends SkillName
case object Ride extends SkillName
case object RifleAndShotgun extends SkillName
case object Science extends SkillName
case object SleightOfHand extends SkillName
case object Spear extends SkillName
case object SpotHidden extends SkillName
case object Law extends SkillName
case object SubmachineGun extends SkillName
case object LibraryUse extends SkillName
case object Throw extends SkillName
case object MachineGun extends SkillName
case object Track extends SkillName
case object Mathematics extends SkillName
case object Whip extends SkillName
case object MechanicalRepair extends SkillName
case object Medicine extends SkillName
